### ISSUE TITLE
Checking if the DS3231 is connected

### ISSUE THREAD

**Issue by Hyperdimensionals** [MajicDesigns/MD_DS3231#12]
Hello,

Is there a way built in to this library to check if the DS3231 module is connected? I looked through the documentation but couldn't find anything. I noticed that the outputted time stays the same when it gets disconnected so that's a way to check, but wanted to see if there was anything built in to get a simple bool answer.

By the way, I greatly appreciate that this library doesn't block when the module gets disconnected as another library I was using did.

Thanks

**Comment by MajicDesigns** [comment]
Use the isRunning() method and read the library documentation to understand exactly what is being reported.

**Comment by Hyperdimensionals** [comment]
I did read the documentation and tried RTC.isRunning() after an RTC.readTime() command and it returned the same through Serial.print whether or not the DS3231 was connected. I also tried the RTC.status() method on some parameters (such as DS3231_CLOCK_HALT not knowing exactly what CLOCK_HALT means) with no difference in output regardless of connection. Forgive my dumbness, I'm new to this, but I didn't find an explanation in the documentation. It's probably something that should be obvious but is not to me...

If you could just give me the line of code to check the connection that would be great. You don't even have to explain it - I'll just work backwards from there.

**Comment by MajicDesigns** [comment]
I really don't understand what you mean by 'check the connection' because it is not clear what you are actually trying to do.

On an I2C bus each device has an address that it responds to. If you want to see if there is a device at that device address, then you need to do it outside the library. Lots of example code to do that, just search for it. The DS3231 device address is hard coded in the device and is found in the datasheet (or you could look in the header file).

If, on the other hand, you want the clock to be turned on (ie actually run), then you need to check the HALTED_FLAG. From the documentation:

> Controls the OSF bit. When ON, this indicates that the oscillator either is stopped or was stopped for some period and may be used to judge the validity of the timekeeping data. It remains ON until turned OFF by user code.

You use control() to turn it off.

I would suggest that you find a datasheet for the device and read up on the functions of the bits as they are basically 1-for-1 with what you can do in control()/status(). The library assumes that you have a basic knowledge of how the chip works even if it tries to create a higher level abstraction of RTC functions.

**Comment by Hyperdimensionals** [comment]
Sorry, I mean when the DS3231 is connected to the Arduino and outputting the time, and one of the power or SDA/SCL pins physically gets unplugged/disconnected in the real world. When this happens, I see that the time outputted by RTC.readTime() is frozen and no longer changes, so comparing the times from one second to another is a way to check, but I thought there must be a more direct way. So It sounds like I would do this with the device address.

I apologize for the imprecise language. But thank you for taking the time to respond.

**Comment by nlangel** [comment]
Way late to the game, but I (also) found if the DS3231 isn't physically present, readTime happily returns "True"
I added a check to the "readDevice" call and now it return true/false depending if the the DS3231 is found:
boolean MD_DS3231::readTime(void)
// Read the current time from the RTC and unpack it into the object variables
// return true if the function succeeded
{
  if (readDevice(ADDR_TIME, bufRTC, 7) == 0) { // <- Changed this
	  return(false);                                           // Added this
  }                                                                     // and this

  // unpack it
  s = BCD2bin(bufRTC[ADDR_SEC]);
  m = BCD2bin(bufRTC[ADDR_MIN]);
#if ENABLE_12H
  if (bufRTC[ADDR_CTL_12H] & CTL_12H) // 12 hour clock
  {
    h = BCD2bin(bufRTC[ADDR_HR] & 0x1f);
    pm = (bufRTC[ADDR_CTL_PM] & CTL_PM);
  }
  else
  {
#endif
    h = BCD2bin(bufRTC[ADDR_HR] & 0x3f);
#if ENABLE_12H
    pm = 0;
  }
#endif
#if ENABLE_DOW
  dow = BCD2bin(bufRTC[ADDR_DAY]);
#endif
  dd = BCD2bin(bufRTC[ADDR_TDATE]);
  mm = BCD2bin(bufRTC[ADDR_MON]);

  yyyy = BCD2bin(bufRTC[ADDR_YR]) + (CENTURY * 100);
  if (bufRTC[ADDR_CTL_100] & CTL_100)
    yyyy += 100;

  return(true);
}

**Comment by MajicDesigns** [comment]
The change suggested and other similar changes have been included in release 1.4.1
