### ISSUE TITLE
Not Really an Issue : PIN assignments

### ISSUE THREAD

**Issue by jagganath69** [MajicDesigns/MD_DS3231#7]
Apologies, as I am just beginning to delve into SBC. I am more into the software side.

I just can't find any reference to pin assignments except the I2C. Does that mean the lib is HARDWIRED to the default pins of the I2C of respective boards? We can't assign any different pins for SDA and SCL instead?

Thank you!

**Comment by MajicDesigns** [comment]
I2C is a bus based communications method that works best with hardware support. Each device connected to the bus has a unique address and communications is established with the device based on this address. 

On most Arduino MCU platforms, there is one set of SDA/SCL pins by default and the _Wire_ library manages the I2C interface. The actual pins are no known and not relevant to the application. The most recent update of this library allows the SDA/SCL pins to be specified for the ESP8266 platform because it has more than one hardware I2C interface available.
